const soupStyles = {
    color: {
        default: 'black',
        primary: '#F2AF9A',
        secondary: '#CF2C51',
        accent: '#3D075E',
        success: '#2F6C67',
        danger: '#EB4E47',
        fun: '#ED8733',
        neutral: '#f6f6f6',
    },
    padding: {
        default: '3%',
        bumper: '5%',
        largeContainer: '5% 2.5%',
        mediumContainer: '2% 1% 1.5% 1%',
        smallContainer: '1% 0.5% 1% 0.5%',
        navs: '4% 0 3% 0',
        inputPlus: '0 2.5%',
        input: '0 1.5%',
        smallButton: '1% 1.5%',
        aLink: '1% 0',
    },
    width: {
        appLevel: '1200px',
        full: '100%',
        nearlyThere: '95%',
        subComponentLevel: '40%',
        navElement: '20%',
        input: '250px',
        smallButton: '60px',
        aLink: '75px',
        thirdSplit: '30.3%',
        quartSplit: '22%',
    },
    margin: {
        appLevel: 'auto', 
        largePlus: '12%',
        large: '10%',
        mediumPlus: '7%',
        medium: '5%',
        small: '1%', 
    },
    display: {
        default: 'flex',
        wrapDefault: 'wrap',
        alignDefault: 'center',
        directionSecondary: 'column',
        justifyDefault: 'space-around',
        justifySecondary: 'space-between',
        justifyTertiary: 'flex-start',
        justifyQuart: 'space-evenly',
        hide: 'none',
    },
    height: {
        componentLevel: '750px',
        subComponentLevel: '55%',
        divider: '60px',
        card: '160px',
        smallCard: '80px',
        input: '40px',
    },
    fontSize: {
        heading: '2.2rem',
        large: '1.7rem',
        medium: '1.4rem',
        small: '1.2rem',
    },
    font: {
        alternate: 'Patrick Hand, cursive',
    },
    text: {
        decorationStandard: 'none',
        transformSecondary: 'lowercase',
    },
    border: {
        radiusStandard: '4px',
        radiusMedium: '3px',
        radiusSmall: '2px',
    },
    cursor: {
        default: 'pointer',
    }
}

export default soupStyles;