export const FETCHING_TOKEN = "FETCHING_TOKEN";
export const TOKEN_FETCHED = "TOKEN_FETCHED";
export const ERROR_FETCHING_TOKEN = "ERROR_FETCHING_TOKEN";

export const FETCHING_USERS = "FETCHING_USERS";
export const USERS_FETCHED = "USERS_FETCHED";
export const PUSH_USERS = "PUSH_USERS";
export const ERROR_FETCHING_USERS = "ERROR_FETCHING_USERS";

export const ADDING_ITEM = "ADDING_ITEM";
export const ITEM_ADDED = "ITEM_ADDED";
export const ERROR_ADDING_ITEM = "ERROR_ADDING_ITEM";

export const DELETING_ITEM = "DELETING_ITEM";
export const ITEM_DELETED = "ITEM_DELETED";
export const ERROR_DELETING_ITEM = "ERROR_DELETING_ITEM";

export const UPDATING_ITEM = "UPDATING_ITEM";
export const ITEM_UPDATED = "ITEM_UPDATED";
export const ERROR_UPDATING_ITEM = "ERROR_UPDATING_ITEM";

export const FILTER_ITEMS = "FILTER_ITEMS";
export const SEARCH_ITEMS = "SEARCH_ITEMS";

export const FETCHING_ITEMS = "FETCHING_ITEMS";
export const ITEMS_FETCHED = "ITEMS_FETCHED";
export const PUSH_ITEMS = "PUSH_ITEMS";
export const ERROR_FETCHING_ITEMS = "ERROR_FETCHING_ITEMS";

export const FETCHING_USER = "FETCHING_USER";
export const USER_FETCHED = "USER_FETCHED";
export const PUSH_USER = "PUSH_USER";
export const ERROR_FETCHING_USER = "ERROR_FETCHING_USER"
