export const FETCHING_TOKEN = "FETCHING_TOKEN";
export const TOKEN_FETCHED = "TOKEN_FETCHED";
export const ERROR_FETCHING_TOKEN = "ERROR_FETCHING_TOKEN";

export const FETCHING_ITEMS = "FETCHING_ITEMS";
export const ITEMS_FETCHED = "ITEMS_FETCHED";
export const PUSH_ITEMS = "PUSH_ITEMS";
export const ERROR_FETCHING_ITEMS = "ERROR_FETCHING_ITEMS";